### ISSUE TITLE
Can you tell me the meaning of Coordinate X&Y?

### ISSUE THREAD

**Issue by Rita-ritally** [AlirezaMorsali/MH-RELU-INR#1]
I read the paper and found no details of the input image parameters in the text, so I looked at the code. I found that the inputs to the whole network are the grey scale map matrix and the Coordinate matrix, which I understand to be the X and Y in the picture respectively. can you please tell me the meaning of the Coordinate matrix and how I can implement it if I want to use it for audio?

**Comment by AlirezaMorsali** [comment]
Coordinate is in general an array of size $N \times D$ where $D$ is the dimensions of the independent variable (for image $D=2$, for audio $D=2$) and $N$ is the number of samples we have (for an image of size $128 \times 128$, we have $N=128*128=16384$, for an audio signal of length $T$ samples $N=T$).
However, the values of the Coordinate array is normalized for example if you have an audio signal $A[n]$ for $n=1,2,\dots, T$, the coordinate is better to be normalized. For example $Coord=[-1, -1+(2/T), \dots,1]$.

**Comment by Rita-ritally** [comment]
Thank you very much for your reply, I have understood it approximately. I am trying to experiment on audio using your proposed network. Can I contact you at any time if I have any questions?

**Comment by AlirezaMorsali** [comment]
I'd be happy to help.

**Comment by AlirezaMorsali** [comment]
> Thank you very much for your reply, I have understood it approximately. I am trying to experiment on audio using your proposed network. Can I contact you at any time if I have any questions?

I'd be happy to help.
